name: Make GitHub Release
run-name: "Making Release: ${{ github.ref_name }}"

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

concurrency:
  group: gh-release
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Mise
        uses: jdx/mise-action@v3

      - name: Install Dependencies
        run: mise setup

      - name: Prepare Release Metadata
        id: meta
        run: |
          # VERSION and IS_PRERELEASE detection
          clean_ver=${VERSION#v}
          echo "VERSION=$clean_ver" >> "$GITHUB_ENV"

          if [[ "$clean_ver" == 0* ]]; then
            echo "IS_PRERELEASE=true" >> "$GITHUB_ENV"
          else
            echo "IS_PRERELEASE=false" >> "$GITHUB_ENV"
          fi

          {
            echo "CHANGELOG<<EOF"
            if [[ -n "$LATEST_TAG" ]]; then
              echo "## What's New?"
              mise run get-changelog
            else
              echo "No changes to note."
            fi
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Build and Package
        run: mise package

      - name: Show Checksums
        run: cat dist/checksums.txt

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
          prerelease: ${{ env.IS_PRERELEASE == 'true' }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
